#### zero()

#### -괄호 안에 입력된 숫자만큼의 원소를 생성하고 0으로 초기화 

In [27]:
import numpy as np
y = np.zeros(shape=(5,2), dtype=np.int8)

y

# x = np.array([1,2,3])
# type(x)
# x.shape


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

#### mean() : 배열에 저장된 원소들의 평균값을 계산

In [31]:
import numpy as np
x = np.array([1,3,4,5])
x.mean()
y = np.array([[1,2,5],[4,6,7]])
y.mean()
y.mean(axis=1)

array([2.66666667, 5.66666667])

#### shape를 잘 이해할 수 있는 예제 

In [32]:
import numpy as np
x = np.array([3,3,3])
x.shape

(3,)

In [33]:
import numpy as np
x = np.array([[3,3,3],[3,3,3]])
x.shape

(2, 3)

In [41]:
import numpy as np
x = np.array([[[3,3,3,3],[3,3,3,3]],[[3,3,3,3],[3,3,3,3]],[[3,3,3,3],[3,3,3,3]]])
x.shape

(3, 2, 4)

#### array() – Numpy 형식으로 배열의 원소를 입력할 때는 반드시 리스트 형식으로 입력


In [37]:
import numpy as np
x = np.array([1,2,3])   # array 만들 때 리스트와 튜플만 가능 set 딕셔너리 안됨.
y = np.array((1,2,3))
z = np.array({1,2,3})
a = np.array({"a":"b","c":"d"})
print(x,y,z,a)

[1 2 3] [1 2 3] {1, 2, 3} {'a': 'b', 'c': 'd'}


#### reshape() – 배열을 원하는 모양으로 생성

In [43]:
import numpy as np
a = [1,2,3,4,5,6,7,8]
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))
print(b,b.shape,'\n',c ,c.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4) 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


#### reshape() – 3차원 배열 만들기

###### reshape를 활용하는 경우를 보다 보면 입력인수로 -1이 들어간 경우가 종종 있다.reshape()의 ‘-1’이 의미하는 바는, 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

In [48]:
import numpy as np
a = np.arange(1,9)
print(a)
b = a.reshape(2,2,2)
print(b)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
import numpy as np
a = np.arange(1,13)
print(a)
b = a.reshape(3,2,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### reshape 의미

###### reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며, 현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [52]:
import numpy as np
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
import numpy as np
x = np.arange(12)
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [55]:
import numpy as np
x = np.arange(12)
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
import numpy as np
x = np.arange(12)
x.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
import numpy as np
x = np.arange(12)
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
import numpy as np
x = np.arange(12)
x.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

#### ones() – 배열을 1의 값들로 채움

In [62]:
import numpy as np
y = np.ones([4,3])
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [66]:
import numpy as np
y = np.ones([4,3])

#### Numpy 배열의 슬라이싱

In [76]:
list1 = [ [1,11],[2,12],[3,13],[4,14] ]
arr = np.array(list1)
# print(arr)
# print(arr[2,1])
# print(arr[:][1])
print(arr[1:4])

[[ 2 12]
 [ 3 13]
 [ 4 14]]


##### math 모듈의 sqrt()와  numpy 모듈의 sqrt() 비교

In [79]:
import math
math.sqrt(2)
math.sqrt([2,3,4])

TypeError: must be real number, not list

In [81]:
import numpy as np
np.sqrt(2)
np.sqrt([2,3,4])

array([1.41421356, 1.73205081, 2.        ])

#### 제로벡터와 제로 행렬

In [83]:
import numpy as np
x = np.zeros(15)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
y = np.zeros([5,3])
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [86]:
z = y.reshape(3,5)
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [87]:
z += 4
print(z)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]


### 전치행렬 
#### – 행과 열을 교환하여 얻어지는 행렬 , 행렬의 값들을 주대각선을 기준으로 위치를 바꾼 행렬을 의미

##### transpose()

In [90]:
import numpy as np
ary =np.array([[1,2] ,[3,4]])
print(ary)
print('\n\n\n\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2]
 [3 4]]





[[1 3]
 [2 4]]


In [91]:
ary =np.array([[1,2,5] ,[3,4,6]])
print(ary)
print('\n\n\n\n')
trans_ary = ary.transpose()
print(trans_ary)

[[1 2 5]
 [3 4 6]]





[[1 3]
 [2 4]
 [5 6]]


#### 2개 배열에 대한 연산
###### – 2개 배열에 저장된 내용을 인덱스별로 계산 

###### – 선형대수학의 사칙연산과 동일하게 작동

###### – 곱셈도 같은 원리로 동작

In [97]:
import numpy as np
x = np.array((3,4,5))
y = np.array((1,2,3))
print(x+y)
print(x*y)
print(x%y)
print(x**y)

[4 6 8]
[ 3  8 15]
[0 0 2]
[  3  16 125]


In [102]:
x = np.array((3,4,5))
x += 1
print(x)
y = list(x)
print(list(x))
y += 1

[4 5 6]
[4, 5, 6]


TypeError: 'int' object is not iterable

#### 인덱싱

In [104]:
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X[1])
print(X[:,1])

[4 5 6]
[2 5 8]


#### 2개의 Numpy 배열 간의 계산

In [108]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(X[0,:]+Y[2,:])

[ 9 11 13]


In [116]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(X[:,1]*Y[2,:])

[16 45 80]


In [117]:
import numpy as np
a = np.array([10, 20, 30, 40, 60])
b = a > 30
print(b)

[False False False  True  True]


#### random

In [120]:
import numpy as np
ary = np.random.random(5)
print(ary)

[0.8369327  0.29043323 0.32376207 0.18140232 0.86627818]


#### rand :만들어진 난수 어레이는 주어진 값에 의해 결정되며, [0, 1) 범위에서 균일한 분포를 갖습니다

In [123]:
a = np.random.rand(5)
print(a)

b = np.random.rand(2, 3)
print(b)

a = np.random.randint(2, size=5)
print(a)

b = np.random.randint(2, 4, size=5)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[0.26750287 0.39698134 0.54664947 0.93209659 0.75979966]
[[0.53022718 0.01777406 0.64870843]
 [0.02236927 0.97727929 0.85354068]]
[0 1 1 0 0]
[2 2 3 2 3]
[[3 1 4]
 [4 2 4]]


#### random.seed()

In [154]:
import numpy as np
np.random.seed(0)
print(np.random.rand(2,3))
np.random.seed(1)
print(np.random.rand(2,3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]]


In [133]:
np.random.seed(0)
a = np.random.rand(5)
a > 0.12
# print(a)

array([ True,  True,  True,  True,  True])

#### any() 와 all() 의 비교

In [139]:
a = np.random.rand(5)
print(a>0.12)
print(np.all(a>0.12))

[ True  True  True  True False]
False


#### linspace()
##### 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분
##### numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [155]:
import numpy as np
np.linspace(0,12,4)

array([ 0.,  4.,  8., 12.])

In [156]:
import numpy as np
np.linspace(0,13,4)

array([ 0.        ,  4.33333333,  8.66666667, 13.        ])

In [161]:
#endpoint=False이면 마지막 값을 제외하고 샘플값을 만들어냄
np.linspace(1,13,5,endpoint =False)

array([ 1. ,  3.4,  5.8,  8.2, 10.6])

In [162]:
#retstep=True이면 샘플 간의 간격을 출력
np.linspace(1,13,5,retstep = True)

(array([ 1.,  4.,  7., 10., 13.]), 3.0)